[server]
    address = "127.0.0.1"
    port = 8888
    workers = 8
    log-file = "./logs"

[resource.cute]
    domain = "localhost:8888"
    root = "/Users/ephraimsiegfried/repos/shared/os/Webserver/data/yeet/dist"
    cgi_bin_dir = "/usr/lib/cgi-bin"
    [resource.cute.remaps]
        "/clients/hello" = "clients/hello.php"
        "/api/messages" = "/cgi-bin/hello.cgi"
        "/messages" = "/cgi-bin/hello.cgi"
        
[resource.popo]
    domain = "localhost:9999"
    root = "./data"
    cgi_bin_dir = "/usr/lib/cgi-bin"
    [resource.popo.remaps]
        "/yay" = "/cgi-bin/cgi"
        "/post" = "/cgi-bin/post.cgi"
