[server]
    port = 8888
    workers = 4
    log-file = "./logs"

[resource.cute]
    domain = "localhost:8888"
    root = "./data"
    cgi_bin_dir = "/usr/lib/cgi-bin"
    [resource.cute.remaps]
        "/clients/hello" = "clients/hello.php"
        "/yay" = "/cgi-bin/cgi"

[resource.popo]
    domain = "localhost:9999"
    root = "./yeet"
    cgi_bin_dir = "/usr/lib/cgi-bin"
    [resource.popo.remaps]
        "/yay" = "/cgi-bin/cgi"
