# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.29.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.29.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ephraimsiegfried/repos/shared/os/webserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ephraimsiegfried/repos/shared/os/webserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.29.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.29.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ephraimsiegfried/repos/shared/os/webserver/CMakeFiles /Users/ephraimsiegfried/repos/shared/os/webserver//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ephraimsiegfried/repos/shared/os/webserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cuteserver

# Build rule for target.
cuteserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuteserver
.PHONY : cuteserver

# fast build rule for target.
cuteserver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/build
.PHONY : cuteserver/fast

deps/hashmap/sc_map.o: deps/hashmap/sc_map.c.o
.PHONY : deps/hashmap/sc_map.o

# target to build an object file
deps/hashmap/sc_map.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/deps/hashmap/sc_map.c.o
.PHONY : deps/hashmap/sc_map.c.o

deps/hashmap/sc_map.i: deps/hashmap/sc_map.c.i
.PHONY : deps/hashmap/sc_map.i

# target to preprocess a source file
deps/hashmap/sc_map.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/deps/hashmap/sc_map.c.i
.PHONY : deps/hashmap/sc_map.c.i

deps/hashmap/sc_map.s: deps/hashmap/sc_map.c.s
.PHONY : deps/hashmap/sc_map.s

# target to generate assembly for a file
deps/hashmap/sc_map.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/deps/hashmap/sc_map.c.s
.PHONY : deps/hashmap/sc_map.c.s

deps/log/log.o: deps/log/log.c.o
.PHONY : deps/log/log.o

# target to build an object file
deps/log/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/deps/log/log.c.o
.PHONY : deps/log/log.c.o

deps/log/log.i: deps/log/log.c.i
.PHONY : deps/log/log.i

# target to preprocess a source file
deps/log/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/deps/log/log.c.i
.PHONY : deps/log/log.c.i

deps/log/log.s: deps/log/log.c.s
.PHONY : deps/log/log.s

# target to generate assembly for a file
deps/log/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/deps/log/log.c.s
.PHONY : deps/log/log.c.s

deps/threadpool/thpool.o: deps/threadpool/thpool.c.o
.PHONY : deps/threadpool/thpool.o

# target to build an object file
deps/threadpool/thpool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/deps/threadpool/thpool.c.o
.PHONY : deps/threadpool/thpool.c.o

deps/threadpool/thpool.i: deps/threadpool/thpool.c.i
.PHONY : deps/threadpool/thpool.i

# target to preprocess a source file
deps/threadpool/thpool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/deps/threadpool/thpool.c.i
.PHONY : deps/threadpool/thpool.c.i

deps/threadpool/thpool.s: deps/threadpool/thpool.c.s
.PHONY : deps/threadpool/thpool.s

# target to generate assembly for a file
deps/threadpool/thpool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/deps/threadpool/thpool.c.s
.PHONY : deps/threadpool/thpool.c.s

deps/tomlparser/toml.o: deps/tomlparser/toml.c.o
.PHONY : deps/tomlparser/toml.o

# target to build an object file
deps/tomlparser/toml.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/deps/tomlparser/toml.c.o
.PHONY : deps/tomlparser/toml.c.o

deps/tomlparser/toml.i: deps/tomlparser/toml.c.i
.PHONY : deps/tomlparser/toml.i

# target to preprocess a source file
deps/tomlparser/toml.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/deps/tomlparser/toml.c.i
.PHONY : deps/tomlparser/toml.c.i

deps/tomlparser/toml.s: deps/tomlparser/toml.c.s
.PHONY : deps/tomlparser/toml.s

# target to generate assembly for a file
deps/tomlparser/toml.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/deps/tomlparser/toml.c.s
.PHONY : deps/tomlparser/toml.c.s

src/cgi_handler.o: src/cgi_handler.c.o
.PHONY : src/cgi_handler.o

# target to build an object file
src/cgi_handler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/cgi_handler.c.o
.PHONY : src/cgi_handler.c.o

src/cgi_handler.i: src/cgi_handler.c.i
.PHONY : src/cgi_handler.i

# target to preprocess a source file
src/cgi_handler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/cgi_handler.c.i
.PHONY : src/cgi_handler.c.i

src/cgi_handler.s: src/cgi_handler.c.s
.PHONY : src/cgi_handler.s

# target to generate assembly for a file
src/cgi_handler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/cgi_handler.c.s
.PHONY : src/cgi_handler.c.s

src/config.o: src/config.c.o
.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/config.c.s
.PHONY : src/config.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/main.c.s
.PHONY : src/main.c.s

src/parser.o: src/parser.c.o
.PHONY : src/parser.o

# target to build an object file
src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/parser.c.o
.PHONY : src/parser.c.o

src/parser.i: src/parser.c.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/parser.c.i
.PHONY : src/parser.c.i

src/parser.s: src/parser.c.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/parser.c.s
.PHONY : src/parser.c.s

src/request.o: src/request.c.o
.PHONY : src/request.o

# target to build an object file
src/request.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/request.c.o
.PHONY : src/request.c.o

src/request.i: src/request.c.i
.PHONY : src/request.i

# target to preprocess a source file
src/request.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/request.c.i
.PHONY : src/request.c.i

src/request.s: src/request.c.s
.PHONY : src/request.s

# target to generate assembly for a file
src/request.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/request.c.s
.PHONY : src/request.c.s

src/response.o: src/response.c.o
.PHONY : src/response.o

# target to build an object file
src/response.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/response.c.o
.PHONY : src/response.c.o

src/response.i: src/response.c.i
.PHONY : src/response.i

# target to preprocess a source file
src/response.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/response.c.i
.PHONY : src/response.c.i

src/response.s: src/response.c.s
.PHONY : src/response.s

# target to generate assembly for a file
src/response.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/response.c.s
.PHONY : src/response.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuteserver.dir/build.make CMakeFiles/cuteserver.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cuteserver"
	@echo "... deps/hashmap/sc_map.o"
	@echo "... deps/hashmap/sc_map.i"
	@echo "... deps/hashmap/sc_map.s"
	@echo "... deps/log/log.o"
	@echo "... deps/log/log.i"
	@echo "... deps/log/log.s"
	@echo "... deps/threadpool/thpool.o"
	@echo "... deps/threadpool/thpool.i"
	@echo "... deps/threadpool/thpool.s"
	@echo "... deps/tomlparser/toml.o"
	@echo "... deps/tomlparser/toml.i"
	@echo "... deps/tomlparser/toml.s"
	@echo "... src/cgi_handler.o"
	@echo "... src/cgi_handler.i"
	@echo "... src/cgi_handler.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/request.o"
	@echo "... src/request.i"
	@echo "... src/request.s"
	@echo "... src/response.o"
	@echo "... src/response.i"
	@echo "... src/response.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

