[server]
    port = 8888
    address = "0.0.0.0"
    workers = 8
    log_file = "./logs"

[resource.cute]
    domain = "nedkitty.pumuckipla.net:8888"
    root = "/content"
    cgi_bin_dir = "/webs/content/cgi-bin"
    [resource.cute.remaps]
        "/clients/hello" = "/cgi-bin/first.cgi"
        "/api/messages" = "/cgi-bin/main.cgi"
        "/messages" = "/cgi-bin/main.cgi"

[resource.notcute]
    domain = "kitty.pumuckipla.net"
    root = "/content"
    cgi_bin_dir = "/webs/content/cgi-bin"
    [resource.cute.remaps]
        "/clients/tschau" = "/cgi-bin/first.cgi"
        "/api/messages" = "/cgi-bin/main.cgi"
        "/messages" = "/cgi-bin/main.cgi"
